name: Django CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository # check out the repository
        uses: actions/checkout@v4

      - name: Set up Python # set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Project Dependencies # install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests # run Django tests
        run: |
          python manage.py test

      - name: Run Django System Check # run Django system check
        run: |
          python manage.py check

      - name: Check for Missing Migrations # check for missing migrations
        run: |
          python manage.py makemigrations --check --dry-run

      - name: Install Semgrep   # install semgrep for static code analysis
        # uses: semgrep/semgrep-action@v1
        #   with:
        #     config: auto
        run: pip install semgrep

      - name: Run Semgrep # run static code analysis using semgrep
        run: semgrep scan --config p/python --config p/django


